language: smalltalk

os:
  - linux

smalltalk:
  - Pharo-6.1
  - Pharo-7.0
  - Pharo64-7.0
  - Pharo-8.0
  - Pharo64-8.0
 
matrix:
  allow_failures:
    - smalltalk: Pharo-8.0
    - smalltalk: Pharo64-8.0
  fash_finish: true
